In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../Data/Raw/Telco-Customer-Churn.csv")

In [9]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [10]:
df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

KeyError: 'TotalCharges'

In [11]:
print(df.columns)

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [12]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(' ', '_')
)

In [13]:
print(df.columns)

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip_Code',
       'Lat_Long', 'Latitude', 'Longitude', 'Gender', 'Senior_Citizen',
       'Partner', 'Dependents', 'Tenure_Months', 'Phone_Service',
       'Multiple_Lines', 'Internet_Service', 'Online_Security',
       'Online_Backup', 'Device_Protection', 'Tech_Support', 'Streaming_TV',
       'Streaming_Movies', 'Contract', 'Paperless_Billing', 'Payment_Method',
       'Monthly_Charges', 'Total_Charges', 'Churn_Label', 'Churn_Value',
       'Churn_Score', 'CLTV', 'Churn_Reason'],
      dtype='str')

In [14]:
df['Total_Charges'] = pd.to_numeric(
    df['Total_Charges'],
    errors='coerce'
)

In [15]:
df.dropna(inplace=True)

In [16]:
df['AvgRevenuePerMonth'] = (
    df['Total_Charges'] /
    (df['Tenure_Months'] + 1)
)

In [23]:
df['LongTermCustomer'] = (
    df['Tenure_Months'] > 24
).astype(int)

In [24]:
df['HighMonthlyCharges'] = (
    df['Monthly_Charges'] >
    df['Monthly_Charges'].median()
).astype(int)

In [25]:
streaming_cols = [
    'Streaming_TV',
    'Streaming_Movies'
]

df['StreamingServicesCount'] = (
    (df[streaming_cols] == 'Yes')
    .sum(axis=1)
)

In [26]:
df['Churn_Label'] = df['Churn_Label'].map({
    'Yes': 1,
    'No': 0
})

In [27]:
df[[
    'AvgRevenuePerMonth',
    'LongTermCustomer',
    'HighMonthlyCharges',
    'StreamingServicesCount',
    'Churn_Label'
]].head()

,AvgRevenuePerMonth,LongTermCustomer,HighMonthlyCharges,StreamingServicesCount,Churn_Label
0,36.050000,0,0,0,NaN
1,50.550000,0,0,0,NaN
2,91.166667,0,1,2,NaN
3,105.036207,1,1,2,NaN
4,100.726000,1,1,2,NaN

In [28]:
df.to_csv(
    "Churn_Feature_Engineered.csv",
    index=False
)